#!/usr/bin/python
'''
Directly call a salt command in the modules, does not require a running salt
minion to run.
'''

try:
    import qubes.mgmt.patches
except ImportError:
    pass

import sys
sys.argv.insert(1, '--local')

from salt.scripts import salt_call


if __name__ == '__main__':
    salt_call() 
