#!/usr/bin/python
'''
Directly call a salt command in the modules, does not require a running salt
minion to run.
'''

import sys
sys.argv.append('--local')

from salt.scripts import salt_call


if __name__ == '__main__':
    salt_call() 
