#!/bin/bash

# Base Packages:
# --------------
# qubes-mgmt-salt
# qubes-mgmt-salt-config
# qubes-mgmt-salt-base
# qubes-mgmt-salt-base-salt
# qubes-mgmt-salt-base-overrides
# qubes-mgmt-salt-base-gpg
# qubes-mgmt-salt-base-yamlscript-renderer
# qubes-mgmt-salt-base-yamlscript-users
# 
# Dom0 Packages:
# --------------
# qubes-mgmt-salt-dom0
# qubes-mgmt-salt-dom0-qvm
# qubes-mgmt-salt-dom0-update
# qubes-mgmt-salt-dom0-virtual-machines
# qubes-mgmt-salt-dom0-fix-permissions
# qubes-mgmt-salt-dom0-policy-qubesbuilder
# qubes-mgmt-salt-dom0-template-upgrade
#
# VM Packages:
# ------------
# qubes-mgmt-salt-vm
# qubes-mgmt-salt-vm-python-pip
#
# Demo packages:
# --------------
# qubes-mgmt-salt-demo
# qubes-mgmt-salt-all-vim
# qubes-mgmt-salt-all-theme
# qubes-mgmt-salt-all-privacy

which apt-get && {
    apt-get remove --purge qubes-salt-config || true
    apt-get autoremove -y

    apt-get remove -y --purge qubes-mgmt-salt-vm || true
    apt-get remove -y --purge qubes-mgmt-salt-dom0 || true
    apt-get remove -y --purge qubes-mgmt-salt || true
    apt-get remove -y --purge qubes-mgmt-salt-base || true
    apt-get remove -y --purge qubes-mgmt-salt-config || true
    apt-get remove -y --purge qubes-mgmt-salt-demo || true
    apt-get autoremove -y
} || {
    yum erase -y qubes-salt-config || true
    yum erase -y qubes-mgmt-salt-vm || true
    yum erase -y qubes-mgmt-salt-dom0 || true
    yum erase -y qubes-mgmt-salt || true
    yum erase -y qubes-mgmt-salt-base || true
    yum erase -y qubes-mgmt-salt-config || true
    yum erase -y qubes-mgmt-salt-demo || true
}
rm -rf /etc/salt/minion.d
rm -rf /var/cache/salt
rm -rf /srv/user*
rm -rf /srv/formulas
rm -rf /srv/pillar
rm -rf /srv/salt
